name: CI

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build and test
    runs-on: windows-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Build app
        working-directory: ./
        shell: bash
        run: |
          unset CI
          npm run setup
          npm run build
          npm run package

          
      - name: Run Azure webapp deploy action using publish profile credentials
        uses: azure/webapps-deploy@v2
        with: 
          app-name: twhite-azure-chat
          slot-name: Production
          publish-profile: ${{ secrets.PUBLISH_PROFILE }}
          package: ./Chat/dist/

  clean-frontend:
    name: Run clean code tests on frontend
    runs-on: windows-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v1

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install (dev) dependencies
        working-directory: ./Chat
        run: npm install

      - name: Lint
        working-directory: ./Chat
        run: npm run lint

      - name: Check all is pretty
        working-directory: ./Chat
        run: npm run prettier:check

      - name: Build
        working-directory: ./Chat
        run: npm run build
